@startuml Decorator

interface IPaciente <<interface>>
class Paciente implements IPaciente
abstract class PacienteDecorator <<abstract>> implements IPaciente
class Diabetes extends PacienteDecorator
class ProblemasCardiacos extends PacienteDecorator
class Alergias extends PacienteDecorator

PacienteDecorator ..> "1" IPaciente

@enduml